[env]
CC_riscv64gc_unknown_scarlet = "riscv64-unknown-linux-gnu-gcc"
CFLAGS_riscv64gc_unknown_scarlet = "-march=rv64gc -mabi=lp64d"
CC_aarch64_unknown_scarlet = "aarch64-unknown-linux-gnu-gcc"

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["compiler-builtins-mem"]
